// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "typst_core";





        [DllImport(__DllName, EntryPoint = "create_compiler", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern Compiler* create_compiler(byte* root, byte* input_path, byte* input_source, byte** font_paths, nuint font_paths_len, byte* package_path, byte* sys_inputs, [MarshalAs(UnmanagedType.U1)] bool ignore_system_fonts);

        [DllImport(__DllName, EntryPoint = "free_compiler", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_compiler(Compiler* compiler);

        [DllImport(__DllName, EntryPoint = "set_sys_inputs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool set_sys_inputs(Compiler* compiler, byte* sys_inputs);

        [DllImport(__DllName, EntryPoint = "compile", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern CompileResult compile(Compiler* compiler, byte* format_ptr, float ppi, byte* pdf_standards);

        [DllImport(__DllName, EntryPoint = "free_compile_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_compile_result(CompileResult result);

        [DllImport(__DllName, EntryPoint = "reset_world", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void reset_world();

        [DllImport(__DllName, EntryPoint = "free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_string(byte* s);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Compiler
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Buffer
    {
        public byte* ptr;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct Warning
    {
        public byte* message;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct CompileResult
    {
        public Buffer* buffers;
        public nuint buffers_len;
        public Warning* warnings;
        public nuint warnings_len;
        public byte* error;
    }



}
